#!/usr/bin/env node
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { argumentsFor, readModel, writeJson } from "./common.mjs";

const args = argumentsFor({
	model: { type: "string" },
	runtime: { type: "boolean", default: false },
});
if (!args.model)
	throw new Error("Usage: node scripts/rl/export.mjs --model PATH [--runtime]");
const model = readModel(args.model);
const portable = {
	format: model.format,
	schema: model.schema,
	features: model.features,
	hiddenSize: model.hiddenSize,
	inputWeights: model.inputWeights,
	hiddenBias: model.hiddenBias,
	outputWeights: model.outputWeights,
};
if (args.runtime) {
	const path = new URL("../../src/commander-model.js", import.meta.url);
	mkdirSync(dirname(path.pathname), { recursive: true });
	writeFileSync(
		path,
		`// Generated by scripts/rl/export.mjs; experimental commander enabled.\nexport const bundledCommanderModel = ${JSON.stringify(portable, null, 2)};\n`,
	);
	console.log(
		"Experimental model installed in src/commander-model.js; simulation owners will use it for initial sides",
	);
} else {
	const path = resolve(args.output, "exported-model.json");
	writeJson(path, portable);
	console.log(`Portable model saved: ${path}`);
}
