export const PERF_COUNTER_DEFAULTS = {
	_version: "V0.27.38",
	_mode: "off",
	_enabled: false,
	plans: 0,
	legacyPlans: 0,
	operationalTaskForces: 0,
	proposals: 0,
	eval: 0,
	neutralBorder: 0,
	recruit: 0,
	unitLoop: 0,
	post: 0,
	prePlans: 0,
	influence: 0,
	smoothing: 0,
	phase0: 0,
	phase67: 0,
	phase133: 0,
	spatialHash: 0,
	frontline: 0,
	frontlineDispatch: 0,
	frontlinePolys: 0,
	frontlineLayoutApply: 0,
	frontlineSlotApply: 0,
	phaseWheel: 0,
	consolidate: 0,
	caches: 0,
	victory: 0,
	aiPosture: 0,
	posture: 0,
	render: 0,
	tickTotal: 0,
	maxTick: 0,
	ticks: 0,
	proposalRuns: 0,
	proposalFailed: 0,
	reassess_noPlan: 0,
	reassess_interval: 0,
	reassess_forced: 0,
	reassess_territory: 0,
	reassess_posture: 0,
	reassess_ratio: 0,
	// unitLoop sub-timers
	unitSetupTerrain: 0,
	unitScanPhase: 0,
	unitEnemyScan: 0,
	unitAllyScan: 0,
	unitGarrisonCoastal: 0,
	unitRetreatMopUp: 0,
	unitRetreatDecision: 0,
	unitGlobalFallback: 0,
	unitFrontlinePress: 0,
	unitMopUpSearch: 0,
	unitMopUpTargetSearch: 0,
	unitCityObjective: 0,
	unitGarrisonTarget: 0,
	unitCombatMove: 0,
	// Tactical-grid workload and stale-target effectiveness counters.
	tacticalFriendlyCandidatePairs: 0,
	tacticalEnemyCandidateVisits: 0,
	tacticalAcceptedPairs: 0,
	tacticalFriendlyPairs: 0,
	tacticalHostileCellVisits: 0,
	tacticalCacheHits: 0,
	tacticalCacheMisses: 0,
	tacticalGhostInvalidations: 0,
	tacticalFastLaneUnits: 0,
	tacticalMaxBucketOccupancy: 0,
	tacticalPeakBucketOccupancy: 0,
	tacticalCellCount: 0,
	tacticalInsertedUnits: 0,
	// Water avoidance debug counters
	coastDeflectHalved: 0,
	knockbackBlocked: 0,
	waterPathPenalized: 0,
	coastStuckAbandoned: 0,
	// Frontline worker lifecycle counters
	frontlineWorkerDispatches: 0,
	frontlineWorkerCompleted: 0,
	frontlineWorkerCoalesced: 0,
	frontlineWorkerErrors: 0,
	frontlineWorkerStaleResults: 0,
	frontlineWorkerLastDurationMs: 0,
	frontlineWorkerMaxDurationMs: 0,
	frontlineWorkerFieldLastDurationMs: 0,
	frontlineWorkerFieldMaxDurationMs: 0,
	frontlineWorkerLayoutDispatches: 0,
	frontlineWorkerLayoutCompleted: 0,
	frontlineWorkerLayoutCoalesced: 0,
	frontlineWorkerLayoutErrors: 0,
	frontlineWorkerLayoutLastDurationMs: 0,
	frontlineWorkerLayoutMaxDurationMs: 0,
};

export function createSimulationMetrics(
	mode = "off",
	defaults = PERF_COUNTER_DEFAULTS,
) {
	return {
		...defaults,
		_mode: mode,
		_enabled: mode !== "off",
		_trackingPaused: false,
		_measurementStart: mode === "off" ? null : performance.now(),
		_traceMarksEnabled: false,
		_history: [],
		_frameHistory: [],
		_frameSpikes: [],
		_longTasks: [],
		_memorySamples: [],
		_frozenReport: null,
		_scheduler: {
			frames: 0,
			renderedFrames: 0,
			skippedRenderFrames: 0,
			requestedSubTicks: 0,
			executedSubTicks: 0,
			cappedSubTickFrames: 0,
			cappedSubTicks: 0,
			accumulatorSum: 0,
			maxAccumulator: 0,
		},
		_lastBenchmark: null,
	};
}

export function getSimulationMetrics(owner) {
	if (owner.perf) return owner.perf;
	if (globalThis.window?.__perf) return globalThis.window.__perf;
	owner.perf = createSimulationMetrics();
	return owner.perf;
}
